name: app
type: nodejs:16

relationships:
  postgresdatabase: "dbpostgres:postgresql"


web:
  commands:
    start: "node main.js"


disk: 512

mounts:
  'run':
    source: local
    source_path: run
